print("starting")
current_year = int(input("Year: "))
current_month = int(input("Month: "))
current_day = int(input("Day: "))
current_hour = int(input("Hour: "))
current_minute = int(input("Minute: "))
current_second = int(input("Second: "))
current_microsecond = int(input("Microsecond: "))
